---
- hosts: all
  vars:
    local_app_dir: "../fog"
    remote_home: "/ec2-user"
    remote_app_dir: "{{ remote_home }}/project"
  gather_facts: false
  pre_tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
    - name: 'install python2'
      raw: sudo apt-get -y install python
    - name: 'install unzip'
      raw: sudo apt-get -y install unzip
  tasks:


    - name: copy zip file
      copy:
        src: "../fog.zip"
        dest: "~{{ remote_app_dir }}/"
    


    - name: unzip
      script: "./unzip_fog.sh"

    - name: copy config file
      copy:
        src: "./config.json"
        dest: "~{{ remote_app_dir }}/fog/config"

    - name: install requirements
      script: "{{ local_app_dir }}/install.sh"
    

    - name: Reboot host and wait for it to restart
      become: yes
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

#    - name: run application
 #     shell: sh /home/ubuntu/ec2-user/project/fog/run_root.sh
  #    async: 999999999999999999999999999999999999999999999999999999
   #   poll: 0

    - name: copy systemd unit file
      become: yes
      copy:
        src: "{{ local_app_dir }}/startapp.service"
        dest: "/etc/systemd/system/"
    - name: enable and start systemd service
      become: yes
      systemd:
        daemon_reload: yes
        state: started
        name: "startapp.service"
        enabled: yes
        